const memefo = {
    subjectsPlural: [
        "bitches",
        "dogs",
        "babies",
        "zebras",
        "friends",
        "parents",
        "money",
        "memes",
        "fame",
        "fortune",
        "hemorrhoids",
        "fire",
        "hipsters",
        "vegans",
        "dinosaurs",
        "birds",
        "cats",
        "Mormons",
        "churches",
        "Christians",
        "children",
        "kids",
        "ghosts",
        "questions",
        "confusion",
        "trees",
        "mountains",
        "lakes",
        "rivers",
        "ugly",
        "pretty",
        "goats",
        "lions",
        "homosexuals",
        "lesbians",
        "gay pride",
        "legislation",
        "revenge",
        "doctors",
        "nurses",
        "corns",
        "fruit",
        "meat",
        "vegetables",
        "monsters",
        "diseases",
        "jobs",
        "schools",
        "science",
        "drugs",
        "cocaine",
        "THC",
        "weed",
        "alchohol",
        "compliments",
        "drunk",
        "high",
        "slutty",
        "poor",
        "froot",
        "sluts",
        "strippers",
        "cars",
        "trucks",
        "Americans",
        "Canadians",
        "midgets",
        "the mentally disabled",
        "retards",
        "abortions",
        "the gays",
        "faggots",
        "cunts",
        "dykes",
        "niggers",
        "naggers",
        "queers",
        "whores",
        "thots",
        "e-girls",
        "Nazis",
        "Catholics",
        "Jews",
        "scrotums",
        "penises",
        "balls",
        "anuses",
        "lies",
        "facts"
    ],
    subjectsSingular: [
        "reality",
        "an anus",
        "a big penis",
        "a Jew",
        "the pope",
        "a nigger",
        "a queer",
        "a whore",
        "a bitch",
        "a dyke",
        "a cunt",
        "bae",
        "your wife",
        "your husband",
        "your hubby",
        "hubby",
        "princess",
        "a dog",
        "some money",
        "a dick",
        "ligma",
        "sugma",
        "a meme",
        "a car",
        "a meal",
        "a big problem",
        "a hemorrhoid",
        "a fire",
        "a bad time",
        "some danger",
        "a ghost",
        "a mouse",
        "a question",
        "a daddy",
        "a father",
        "a mother",
        "a mom",
        "a gift",
        "a nice time",
        "AIDS",
        "death",
        "carl",
        "dave",
        "a tree",
        "a mountain",
        "a goat",
        "a gay",
        "a lesbian",
        "a homosexual",
        "a corn",
        "a dildo",
        "a job",
        "a school",
        "a robot",
        "Jesus",
        "Ariana Grande",
        "Megan Fox",
        "Patrick",
        "a stripper",
        "a retard",
        "daddy",
        "Michael Jackson",
        "Drake",
        "a douchebag",
        "a douche",
        "a faggot",
        "my dad",
        "my grandpa",
        "my grandma",
        "my friend",
        "my dick",
        "my vagina",
        "my body",
        "my boobs",
        "my brain",
        "my ideas",
        "my thoughts",
        "my hands",
        "my feet",
        "my eyes",
        "my mouth",
        "an intellectual",
        "a thot",
        "Hitler",
        "Donald Trump",
        "The United States"
    ],
    verbs: [
        "fuck",
        "eat",
        "shoot",
        "destroy",
        "talk",
        "walk",
        "touch",
        "fire",
        "lick",
        "smite",
        "please",
        "befriend",
        "be gay",
        "be anger",
        "anger",
        "congratulate",
        "consider",
        "run",
        "drown",
        "shave",
        "explode",
        "slurp",
        "exhale",
        "inhale",
        "tickle",
        "free",
        "jail",
        "slave",
        "yeet",
        "greet",
        "slap",
        "hug",
        "kiss",
        "kick",
        "bounce",
        "leave",
        "ditch",
        "join",
        "show",
        "smoke",
        "grow",
        "sleep",
        "win",
        "lose",
        "tie",
        "fly",
        "zip",
        "bop",
        "shop",
        "abort",
        "help",
        "drink",
        "murder",
        "protec",
        "attac",
        "love",
        "sext",
        "strangle",
        "bury",
        "fondle",
        "cut",
        "see",
        "punch",
        "donkey punch",
        "sit on",
        "flash",
        "pay",
        "create",
        "include",
        "buy",
        "sell",
        "require",
        "grab",
        "kill",
        "rape",
        "molest",
        "shank",
        "smell",
        "taste",
        "feel",
        "hear"
    ]
}
memefo.subjects = [...memefo.subjectsPlural,...memefo.subjectsSingular];
