const memefo = {
    subjectsPlural: [
        "bitches",
        "dogs",
        "babies",
        "zebras",
        "friends",
        "parents",
        "money",
        "memes",
        "fame",
        "fortune",
        "hemorrhoids",
        "fire",
        "hipsters",
        "vegans",
        "dinosaurs",
        "birds",
        "cats",
        "mormons",
        "churches",
        "christians",
        "children",
        "kids",
        "ghosts",
        "questions",
        "confusion",
        "trees",
        "mountains",
        "lakes",
        "rivers",
        "ugly",
        "pretty",
        "goats",
        "lions",
        "homosexuals",
        "lesbians",
        "gay pride",
        "legislation",
        "revenge",
        "doctors",
        "nurses",
        "corns",
        "fruit",
        "meat",
        "vegetables",
        "monsters",
        "diseases",
        "jobs",
        "schools",
        "science",
        "drugs",
        "cocaine",
        "THC",
        "weed",
        "alchohol",
        "compliments",
        "drunk",
        "high",
        "slutty",
        "poor",
        "froot",
        "sluts",
        "strippers",
        "cars",
        "trucks",
        "Americans",
        "Canadians",
        "midgets",
        "the mentally disabled",
        "retards",
        "abortions"
    ],
    subjectsSingular: [
        "bae",
        "your wife",
        "your husband",
        "your hubby",
        "hubby",
        "princess",
        "a dog",
        "some money",
        "a dick",
        "ligma",
        "sugma",
        "a meme",
        "a car",
        "a meal",
        "a big problem",
        "a hemorrhoid",
        "a fire",
        "a bad time",
        "some danger",
        "a ghost",
        "a mouse",
        "a question",
        "a daddy",
        "a father",
        "a mother",
        "a mom",
        "a gift",
        "a nice time",
        "AIDS",
        "death",
        "carl",
        "dave",
        "a tree",
        "a mountain",
        "a goat",
        "a gay",
        "a lesbian",
        "a homosexual",
        "a corn",
        "a dildo",
        "a job",
        "a school",
        "a robot",
        "Jesus",
        "Ariana Grande",
        "Megan Fox",
        "Patrick",
        "a stripper",
        "a retard"
    ],
    verbs: [
        "fuck",
        "eat",
        "shoot",
        "destroy",
        "talk",
        "walk",
        "touch",
        "fire",
        "lick",
        "smile to",
        "please",
        "befriend",
        "anger",
        "congratulate",
        "consider",
        "run",
        "drown",
        "shave",
        "explode",
        "slurp",
        "exhale",
        "inhale",
        "tickle",
        "free",
        "jail",
        "slave",
        "yeet",
        "greet",
        "slap",
        "hug",
        "kiss",
        "kick",
        "bounce",
        "leave",
        "ditch",
        "join",
        "show",
        "smoke",
        "grow",
        "sleep",
        "win",
        "lose",
        "tie",
        "fly",
        "zip",
        "bop",
        "shop",
        "abort",
        "help",
        "drink",
        "murder",
        "protec",
        "attac"
    ]
}
memefo.subjects = [...memefo.subjectsPlural,...memefo.subjectsSingular];
